"""create room type and amenity tables

Revision ID: 535d4ecf62b3
Revises: 45902503671b
Create Date: 2026-09-25 22:38:52.288123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535d4ecf62b3'
down_revision: Union[str, Sequence[str], None] = '45902503671b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenity')),
    sa.UniqueConstraint('code', name=op.f('uq_amenity_code'))
    )
    op.create_table('room_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_adults', sa.SmallInteger(), nullable=False),
    sa.Column('max_children', sa.SmallInteger(), nullable=False),
    sa.Column('size_m2', sa.SmallInteger(), nullable=True),
    sa.Column('units_count', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_adults >= 1', name=op.f('ck_room_type_max_adults_positive')),
    sa.CheckConstraint('max_children >= 0', name=op.f('ck_room_type_max_children_not_negative')),
    sa.CheckConstraint('size_m2 IS NULL OR size_m2 > 0', name=op.f('ck_room_type_size_m2_positive')),
    sa.CheckConstraint('units_count >= 1', name=op.f('ck_room_type_units_count_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_type'))
    )
    op.create_table('amenity_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('fr', 'en', 'it', 'de', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('fr', 'en', 'it', 'de')", name=op.f('ck_amenity_translation_locale')),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], name=op.f('fk_amenity_translation_amenity_id_amenity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenity_translation')),
    sa.UniqueConstraint('amenity_id', 'locale', name=op.f('uq_amenity_translation_amenity_id_locale'))
    )
    op.create_table('room_type_amenity',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], name=op.f('fk_room_type_amenity_amenity_id_amenity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], name=op.f('fk_room_type_amenity_room_type_id_room_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_type_id', 'amenity_id', name=op.f('pk_room_type_amenity'))
    )
    op.create_table('room_type_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('fr', 'en', 'it', 'de', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bed_description', sa.String(length=150), nullable=True),
    sa.Column('meta_title', sa.String(length=70), nullable=True),
    sa.Column('meta_description', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('fr', 'en', 'it', 'de')", name=op.f('ck_room_type_translation_locale')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], name=op.f('fk_room_type_translation_room_type_id_room_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_type_translation')),
    sa.UniqueConstraint('locale', 'slug', name=op.f('uq_room_type_translation_locale_slug')),
    sa.UniqueConstraint('room_type_id', 'locale', name=op.f('uq_room_type_translation_room_type_id_locale'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_type_translation')
    op.drop_table('room_type_amenity')
    op.drop_table('amenity_translation')
    op.drop_table('room_type')
    op.drop_table('amenity')
    # ### end Alembic commands ###
