"""create media and room photo tables

Revision ID: 2ec18e05b89e
Revises: 535d4ecf62b3
Create Date: 2026-09-25 22:58:49.302507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ec18e05b89e'
down_revision: Union[str, Sequence[str], None] = '535d4ecf62b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_asset')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_asset_storage_key'))
    )
    op.create_table('media_asset_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('fr', 'en', 'it', 'de', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('fr', 'en', 'it', 'de')", name=op.f('ck_media_asset_translation_locale')),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], name=op.f('fk_media_asset_translation_media_asset_id_media_asset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_asset_translation')),
    sa.UniqueConstraint('media_asset_id', 'locale', name=op.f('uq_media_asset_translation_media_asset_id_locale'))
    )
    op.create_table('room_type_photo',
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], name=op.f('fk_room_type_photo_media_asset_id_media_asset'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], name=op.f('fk_room_type_photo_room_type_id_room_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_type_id', 'media_asset_id', name=op.f('pk_room_type_photo'))
    )
    op.create_index('uq_room_type_photo_one_cover_per_room', 'room_type_photo', ['room_type_id'], unique=True, postgresql_where=sa.text('is_cover'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_room_type_photo_one_cover_per_room', table_name='room_type_photo', postgresql_where=sa.text('is_cover'))
    op.drop_table('room_type_photo')
    op.drop_table('media_asset_translation')
    op.drop_table('media_asset')
    # ### end Alembic commands ###
