"""create season tables

Revision ID: 1f25d8aa3102
Revises: 2ec18e05b89e
Create Date: 2026-09-25 23:12:30.089335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f25d8aa3102'
down_revision: Union[str, Sequence[str], None] = '2ec18e05b89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('period', postgresql.DATERANGE(), sa.Computed("daterange(start_date, end_date, '[]')", persisted=True), nullable=False),
    sa.Column('min_nights', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('period'), '&&'), using='gist', name='ex_season_no_overlap'),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_season_dates_in_order')),
    sa.CheckConstraint('min_nights IS NULL OR min_nights >= 1', name=op.f('ck_season_min_nights_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season'))
    )
    op.create_table('season_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('fr', 'en', 'it', 'de', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('fr', 'en', 'it', 'de')", name=op.f('ck_season_translation_locale')),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_season_translation_season_id_season'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season_translation')),
    sa.UniqueConstraint('season_id', 'locale', name=op.f('uq_season_translation_season_id_locale'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_translation')
    op.drop_table('season')
    # ### end Alembic commands ###
