"""add room base price and season rates

Revision ID: 3df4dab22119
Revises: 1f25d8aa3102
Create Date: 2026-09-25 23:15:06.837983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df4dab22119'
down_revision: Union[str, Sequence[str], None] = '1f25d8aa3102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_rate',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_season_rate_price_positive')),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], name=op.f('fk_season_rate_room_type_id_room_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_season_rate_season_id_season'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id', 'room_type_id', name=op.f('pk_season_rate'))
    )
    op.add_column('room_type', sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # Ajouté à la main : Alembic ne détecte pas les CHECK ajoutés à une table existante.
    op.create_check_constraint(
        op.f('ck_room_type_base_price_positive'),
        'room_type',
        'base_price IS NULL OR base_price > 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_room_type_base_price_positive'), 'room_type', type_='check')
    op.drop_column('room_type', 'base_price')
    op.drop_table('season_rate')
    # ### end Alembic commands ###
