"""create booking request table

Revision ID: 64f5bf95f937
Revises: 3df4dab22119
Create Date: 2026-09-26 15:05:45.015704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64f5bf95f937'
down_revision: Union[str, Sequence[str], None] = '3df4dab22119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=20), sa.Computed("'GF-' || lpad(id::text, 5, '0')", persisted=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'declined', 'cancelled', name='booking_status', native_enum=False, length=20), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=150), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('adults', sa.SmallInteger(), nullable=False),
    sa.Column('children', sa.SmallInteger(), nullable=False),
    sa.Column('children_ages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nights_count', sa.SmallInteger(), nullable=False),
    sa.Column('quoted_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guest_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('prefers_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.Enum('fr', 'en', 'it', 'de', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('fr', 'en', 'it', 'de')", name=op.f('ck_booking_request_locale')),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'declined', 'cancelled')", name=op.f('ck_booking_request_status')),
    sa.CheckConstraint('adults >= 1', name=op.f('ck_booking_request_adults_positive')),
    sa.CheckConstraint('check_out > check_in', name=op.f('ck_booking_request_dates_in_order')),
    sa.CheckConstraint('children >= 0', name=op.f('ck_booking_request_children_not_negative')),
    sa.ForeignKeyConstraint(['handled_by_id'], ['admin_user.id'], name=op.f('fk_booking_request_handled_by_id_admin_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], name=op.f('fk_booking_request_room_type_id_room_type'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_request')),
    sa.UniqueConstraint('reference', name=op.f('uq_booking_request_reference'))
    )
    op.create_index('ix_booking_request_check_in', 'booking_request', ['check_in'], unique=False)
    op.create_index(op.f('ix_booking_request_room_type_id'), 'booking_request', ['room_type_id'], unique=False)
    op.create_index('ix_booking_request_status_created_at', 'booking_request', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_request_status_created_at', table_name='booking_request')
    op.drop_index(op.f('ix_booking_request_room_type_id'), table_name='booking_request')
    op.drop_index('ix_booking_request_check_in', table_name='booking_request')
    op.drop_table('booking_request')
    # ### end Alembic commands ###
