"""create login attempt table

Revision ID: 45902503671b
Revises: c52f3b735062
Create Date: 2026-09-25 19:18:14.409864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45902503671b'
down_revision: Union[str, Sequence[str], None] = 'c52f3b735062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempt'))
    )
    op.create_index('ix_login_attempt_email_created_at', 'login_attempt', ['email', 'created_at'], unique=False)
    op.create_index('ix_login_attempt_ip_address_created_at', 'login_attempt', ['ip_address', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempt_ip_address_created_at', table_name='login_attempt')
    op.drop_index('ix_login_attempt_email_created_at', table_name='login_attempt')
    op.drop_table('login_attempt')
    # ### end Alembic commands ###
