"""create hotel settings tables

Revision ID: d161c9db377a
Revises: 
Create Date: 2026-09-25 18:05:24.702555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd161c9db377a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('stars', sa.SmallInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_out_time', sa.Time(), nullable=False),
    sa.Column('eur_to_mga_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('show_mga_prices', sa.Boolean(), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=True),
    sa.Column('stat', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name=op.f('ck_hotel_settings_stars_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_settings'))
    )
    op.create_table('social_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_link'))
    )
    op.create_table('hotel_settings_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Enum('fr', 'en', 'it', 'de', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=70), nullable=True),
    sa.Column('meta_description', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('fr', 'en', 'it', 'de')", name=op.f('ck_hotel_settings_translation_locale')),
    sa.ForeignKeyConstraint(['settings_id'], ['hotel_settings.id'], name=op.f('fk_hotel_settings_translation_settings_id_hotel_settings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_settings_translation')),
    sa.UniqueConstraint('settings_id', 'locale', name=op.f('uq_hotel_settings_translation_settings_id_locale'))
    )
    op.create_index(op.f('ix_hotel_settings_translation_settings_id'), 'hotel_settings_translation', ['settings_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotel_settings_translation_settings_id'), table_name='hotel_settings_translation')
    op.drop_table('hotel_settings_translation')
    op.drop_table('social_link')
    op.drop_table('hotel_settings')
    # ### end Alembic commands ###
