"""create review table

Revision ID: 797bfde7b000
Revises: 64f5bf95f937
Create Date: 2026-09-26 16:14:57.838000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797bfde7b000'
down_revision: Union[str, Sequence[str], None] = '64f5bf95f937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status', native_enum=False, length=20), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('author_country', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('locale', sa.Enum('fr', 'en', 'it', 'de', name='locale', native_enum=False, length=5), nullable=False),
    sa.Column('stayed_on', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_reply', sa.Text(), nullable=True),
    sa.Column('moderated_by_id', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locale IN ('fr', 'en', 'it', 'de')", name=op.f('ck_review_locale')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_review_status')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_review_rating_range')),
    sa.ForeignKeyConstraint(['moderated_by_id'], ['admin_user.id'], name=op.f('fk_review_moderated_by_id_admin_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_index('ix_review_ip_hash_created_at', 'review', ['ip_hash', 'created_at'], unique=False)
    op.create_index('ix_review_status_created_at', 'review', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_status_created_at', table_name='review')
    op.drop_index('ix_review_ip_hash_created_at', table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
